{
 "title": "Quick Look - Log Time",
 "description": "A dashboard designed for a quick readout by those working in the pit;",
 "time": { "from": "2023-04-18T01:20:50.034Z", "to": "2023-04-18T01:30:50.034Z" },
 "templating": {
  "list": [
   {
    "name": "Timestamp",
    "query": "SELECT CONCAT('[', DATE_FORMAT(log_timestamp, '%b %D %Y, %T'), ']', '(', UNIX_TIMESTAMP(log_timestamp), ')') FROM garbage.metrics;"
   }
  ]
 },
 "panels": [
  { "title": "Current Time", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Next Queue",
   "type": "grafana-clock-panel",
   "description": "Stop work and begin queueing at this time.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 }
  },
  {
   "title": "Metrics",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "garbage",
     "rawSql": "SELECT `group`, MAX(stoplight) FROM garbage.metrics WHERE UNIX_TIMESTAMP(log_timestamp) = ${Timestamp} GROUP BY `group`, log_timestamp LIMIT 50"
    }
   ]
  },
  {
   "title": "Swerve Warnings",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "garbage",
     "rawSql": "SELECT metric as 'Metric', stoplight as 'Stoplight', value as 'Value' FROM garbage.metrics WHERE `group` = 'swerve' AND UNIX_TIMESTAMP(log_timestamp) = ${Timestamp} AND stoplight >= 1 GROUP BY metric, value, stoplight LIMIT 50"
    }
   ]
  },
  {
   "title": "RoboRIO Warnings",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "dataset": "garbage",
     "rawSql": "SELECT metric as 'Metric', stoplight as 'Stoplight', value as 'Value' FROM garbage.metrics WHERE `group` = 'roborio' AND UNIX_TIMESTAMP(log_timestamp) = ${Timestamp} AND stoplight >= 1 GROUP BY metric, value, stoplight LIMIT 50"
    }
   ]
  },
  {
   "title": "PDH Warnings",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "dataset": "garbage",
     "rawSql": "SELECT metric as 'Metric', stoplight as 'Stoplight', value as 'Value' FROM garbage.metrics WHERE `group` = 'pdh' AND UNIX_TIMESTAMP(log_timestamp) = ${Timestamp} AND stoplight >= 1 GROUP BY metric, value, stoplight LIMIT 50"
    }
   ]
  },
  {
   "title": "Elevator Warnings",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "garbage",
     "rawSql": "SELECT metric as 'Metric', stoplight as 'Stoplight', value as 'Value' FROM garbage.metrics WHERE `group` = 'elevator' AND UNIX_TIMESTAMP(log_timestamp) = ${Timestamp} AND stoplight >= 1 GROUP BY metric, value, stoplight LIMIT 50"
    }
   ]
  },
  {
   "title": "Arm Warnings",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "dataset": "garbage",
     "rawSql": "SELECT metric as 'Metric', stoplight as 'Stoplight', value as 'Value' FROM garbage.metrics WHERE `group` = 'arm' AND UNIX_TIMESTAMP(log_timestamp) = ${Timestamp} AND stoplight >= 1 GROUP BY metric, value, stoplight LIMIT 50"
    }
   ]
  },
  {
   "title": "Manipulator Warnings",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "dataset": "garbage",
     "rawSql": "SELECT metric as 'Metric', stoplight as 'Stoplight', value as 'Value' FROM garbage.metrics WHERE `group` = 'manipulator' AND UNIX_TIMESTAMP(log_timestamp) = ${Timestamp} AND stoplight >= 1 GROUP BY metric, value, stoplight LIMIT 50"
    }
   ]
  }
 ]
}